table-of-contents: true
shift-heading-level-by: -1
number-sections: true
highlight-style: tango
variables:
  documentclass: article
  papersize: a4
  geometry:
    - top=20mm
    - left=20mm
    - right=20mm
    - heightrounded
  colorlinks: true
pdf-engine: pdflatex # relevant for reproducibility, see include-before-body
include-before-body: pdf_conversion/before_body.tex
include-in-header: pdf_conversion/in_header.tex
# for the bibliography
citeproc: true
csl: pdf_conversion/ieee.csl
bibliography: references.bib