name: Convert certain .md to .pdf (see the pdf_conversion directory)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pandoc and pdflatex
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-extra

    - name: Modify and prepare main documentation files
      run: |
        # remove everything up to "## Guide for"
        sed -i '1,/^\s*## Guide for/ {/## Guide for/ !d}' janno_r_package.md
        sed -i '1,/^\s*## Guide for/ {/## Guide for/ !d}' qjanno.md
        sed -i '1,/^\s*## Guide for/ {/## Guide for/ !d}' trident.md
        sed -i '1,/^\s*## Guide for/ {/## Guide for/ !d}' xerxes.md

    - name: Convert files
      run: |
        { cat pdf_conversion/pdf_conversion_list.tsv; echo; } | while read -r src dest
        do
            echo "now rendering:" $src "->" $dest
            pandoc $src -o $dest -d pdf_conversion/pandoc_pdf_config.yml
        done

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff -- \*.pdf --quiet HEAD; then
          echo "no changes to commit"
        else
          git commit \*.pdf
          git commit -m "update .pdf documents"
          git push
        fi